### PR TITLE
introduce lazy parsing using a tokenizer

### PR DESCRIPTION
**Pull request by indietyp**
This PR enables lazy parsing from consumers of external crates, that cannot use the `Parser` interface. While it is event-driven, it does not allow for incremental parsing.

This PR introduces the aforementioned capability by moving large parts of the parsing (except for object and array handling, which needs more context) into a tokenizer. As a nice side-effect, it also increases the separation of concerns.

The job of the tokenizer is simple: take an input stream, and once `next()` (or `peek()`) is called, take the next non-whitespace character and convert it to a token if possible.

There is one notable other side-effect, due to the very nature of tokenization, when looking at the object key, it will still create the token, even if it is not a string, meaning in case of an error we might create a `JsonNumber` where not necessary. I think that, due to this being an error case and only being the case in a single instance, this is fine.

## Currently Missing

* Documentation

> Feel free to close the issue if this is a non-goal for the crate. Thank you very much for creating such a promising library!

### CODE REVIEW

**Comment by ecton** [comment]
Thank you for this pull request. I had previously went through an iteration where this approach was used, but I wasn't able to get it to go fast enough. In the end, the only way I was able to get the fastest parsing was to get rid of this style of parsing.

I tried running `cargo bench -p benchmarks` against the main branch and then against this version, and on my machine, this pull request slows down the benchmarks anywhere from 29%-51%. If you're able to submit a pull request that preserves the speed of the `main` branch and introduces this feature, I will gladly accept it!

Thank you again for looking into improving this library!

**Comment by indietyp** [comment]
Employing `Eq` and `Hash`, as well as switching from an internal iterator in `ByteIterator` to a combination of `offset` + `slice` I was able to remove any speed regressions (at least on my machine)

**Comment by ecton** [comment]
Sorry for the delay in testing these new changes out. It looks like you figured out what I couldn't when I was trying last time!

I want to do a closer read-through of the changes before merging now that the performance is on-par.

Thank you again for this!

**Comment by ecton** [comment]
To keep the git history clean with a local mess I created, I ended up using a rebase which tricked github into not noticing this PR is completed. Your commits are still all preserved in the main branch's history, just under different SHAs that on this PR. Oops!

The only changes I ended up making are in this commit: 7ccc58c972072c7c0aa467724cf4d2403233f129. If you have any feedback on the changes I made let me know!

I'm going to hold off on releasing a new version for a little bit (a week or so) in case I get motivated to do anything else to add to the release.

Thank you for contributing!

**Comment by indietyp** [comment]
The changes looked great! Thanks for cleaning up after me 😅 The only comment I have is that peek_char isn't public. I think that is the correct decision, but it makes Array parsing and Object parsing harder. 

My thought, which I can add in a follow up PR, would be to add a supplemental peek type that is publicly exposed, like:

```
fn peek() -> Option<TokenIdent>;

enum TokenIdent {
  Literal,
  Array,
  ArrayEnd,
  String,
  Object,
  Number,
  ObjectEnd,
  Unrecognized
}
```

This would allow other APIs to implement similar functionality that we currently rely on for Array, but with increased type safty. What do you think?

(API does not return Result, because peeking in a character stream is valid, we just don't know the type of the next thing might be)

> sorry for any formatting mistakes and such, I am currently writing this on my phone^^

**Comment by ecton** [comment]
For writing that on your phone, there's surprisingly few mistakes! :) Making that private was a choice purely because it felt weird to return characters rather than tokens, and it's why I added the Iterator interface. Since it's an iterator, users can use `std::iter::Peekable` with it. There are downsides to that too -- for example, currently Peekable doesn't allow accessing the inner type even with read-only access, so you couldn't use the `offset()` function if you wrap it in a Peekable.

Because Peekable isn't super-ergonomic, I would be open to re-exposing peek using something like you proposed. How do you feel about the new type being called `PeekedTokenKind` -- it's a little verbose, but unless you think you'd use this type in another context than peek, I think the name describes its purpose nicely.

I'd love another pull request if you don't mind. Otherwise, I'll still take this feedback into account!

**Pull request closed without merging**
